[package]
name = "rust_cam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
gstreamer = "0.21.2"
rust_gpiozero = "0.2.1"
